#!/usr/bin/env groovy
pipeline {
     agent any

    tools {
      nodejs "Node-12.13.1"
    }

     stages {
        stage("Prepare") {
          steps {
              echo "executing yarn..."
              sh "yarn install"
              sh "yarn --version"
          }
        }
    }
}